### ISSUE TITLE
Failed to resolve imports

### ISSUE THREAD

**Issue by BayBreezy** [StevenJPx2/nugget#4]
Hello @StevenJPx2 ,

I tried the module and got this error

```bash
Pre-transform error: Failed to resolve import ".../node_modules/@fdcn/nugget/dist/functions/plugin" from "virtual:nuxt:/.../.nuxt/plugins/client.mjs". Does the file exist?
```

I also get this error when i visit the browser

![image](https://github.com/StevenJPx2/nugget/assets/53905713/c6f4d54f-7b41-49f9-81dd-4ff0f546137b)

**Comment by StevenJPx2** [comment]
It should be fixed now.

**Comment by BayBreezy** [comment]
@StevenJPx2 Thank you. The issue is now fixed
